config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :game, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :cart, only: %i[create destroy]
  resources :publisher, only: %i[index show]
  resources :platform, only: %i[index show]
  resources :genre, only: %i[index show]
  get "welcome/index"
  root "welcome#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    get "view", to: "checkout#view", as: "checkout_view"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :genre
  belongs_to :platform
  belongs_to :publisher

  validates :game_name, :price, :release_year, presence: true
  validates :game_name, uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games, dependent: :destory

  validates :genre_name, presence: true
  validates :genre_name, uniqueness: true
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :games, dependent: :destory

  validates :platform_name, presence: true
  validates :platform_name, uniqueness: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users, dependent: :destory
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :games, dependent: :destory

  validates :publisher_name, presence: true
  validates :publisher_name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :address, :city, presence: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  # POST /cart
  # data is sent as form data (params)
  def create
    id = params[:id].to_i
    return if session[:shopping_cart].include?(id)

    session[:shopping_cart] << id # push id onto the end of the cart array
    game = Game.find(id)
    flash[:notice] = "➕ #{game.game_name} added to cart!"
  end
end

# DELETE /cart/:id
def destroy
  id = params[:id].to_i
  session[:shopping_cart].delete(id)
  game = Game.find(id)
  flash[:notice] = "➖ #{game.game_name} removed from cart!"
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def create
    # establish a connection to Stripe and Redirect the user to the payment screen
    product = Game.find(params[:id])

    if product.nil?
      redirect_to root_path
      return
    end

    @session = Stripe::Checkout::Session.create(
      payment_method_types: ["card"],
      success_url:          checkout_success_url,
      cancel_url:           checkout_cancel_url,
      line_items:           [
        name:     product.game_name,
        amount:   (product.price * 100).to_i,
        currency: "cad",
        quantity: 1
      ]
    )
    redirect_to @session.url, allow_other_host: true
  end

  def success
    # we took the customers money
  end

  def cancel
    # something went wrong with the payment
  end

  def view
    # see the cart
  end
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    @games = Game.includes(:genre).page params[:page]
  end

  def show
    @game = Game.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @games_search = Game.where("game_name LIKE ?", wildcard_search)
  end
end

app/controllers/genre_controller.rb
class GenreController < ApplicationController
  def index
    @genres = Genre.page params[:page]
  end

  def show
    @genre = Genre.find(params[:id])
  end
end

app/controllers/platform_controller.rb
class PlatformController < ApplicationController
  def index
    @platforms = Platform.page params[:page]
  end

  def show
    @platform = Platform.find(params[:id])
  end
end

app/controllers/publisher_controller.rb
class PublisherController < ApplicationController
  def index
    @publishers = Publisher.page params[:page]
  end

  def show
    @publisher = Publisher.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @games = Game.all.limit(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/platform_helper.rb
module PlatformHelper
end

app/helpers/publisher_helper.rb
module PublisherHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/game/index.html.erb
<h2 class = "title is-2">Games#index</h2>
<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Release Year</th>
      <th>Price</th>
      <th>Genre</th>
      <th>Publisher</th>
      <th>Platform</th>
    </tr>
  </thead>

  <tbody>
  <% @games.each do |game| %>
    <tr>
      <td><%= link_to game.game_name, game %></td>
      <td><%= game.release_year %></td>
      <td><%= game.price %></td>
      <td><%= link_to game.genre.genre_name, game.genre %></td>
      <td><%= link_to game.publisher.publisher_name, game.publisher %></td>
      <td><%= link_to game.platform.platform_name, game.platform %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @games %>

app/views/game/search.html.erb
<p class="mb-5">
  Found <%= pluralize(@games_search.count, 'game') %> when searching for: <%= params[:keywords] %>
</p>
<ul>
  <% @games_search.each do |game|%>
    <li><%= link_to game.game_name, game %> </li>
  <% end %>
</ul>

app/views/game/show.html.erb
<div class="container">
  <div class="row">
    <div class = "col d-flex justify-content-center">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= @game.game_name %></h5>
        </div>
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><strong> Platform: </strong> <%= link_to @game.platform.platform_name, @game.platform %></li>
          <li class="list-group-item"><strong> Genre: </strong> <%= link_to @game.genre.genre_name, @game.genre %></li>
          <li class="list-group-item"><strong> Release Year: </strong> <%= @game.release_year %></li>
          <li class="list-group-item"><strong> Price: </strong> <%= @game.price%>$CAD</li>
          <li class="list-group-item"><strong> Publisher: </strong> <%= link_to @game.publisher.publisher_name, @game.publisher %></li>
        </ul>
        <div class="card-body">

          <% if cart.include?(@game)%>
            <%= button_to cart_path(@game), method: :delete do %>
            ➖Remove from Cart
          <% end %>

          <% else %>
            <%= form_with url: cart_index_path, method: :post do %>
            <%= hidden_field_tag(:id, @game.id) %>
            <%= button_tag "Add to Cart!" %>
          <% end %>

          <% end %>

            <%= form_with url: checkout_create_path, remote: true do %>
            <%= hidden_field_tag(:id, @game.id) %>
            <%= button_tag "Buy Now!!" %>
          <% end %>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/genre/index.html.erb
<h2 class = "title is-2">Genre#index</h2>
<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
  <% @genres.each do |genre| %>
    <tr>
      <td><%= link_to genre.genre_name, genre %></td>
    </tr>
  <% end %>
  </tbody>
</table>
  <%= paginate @genres %>

app/views/genre/show.html.erb
<h1>Genre#show</h1>
<h2 class="title is-2"><%= @genre.genre_name %></h2>

<p>
  <%= @genre.genre_name %> has <%= @genre.games.count %> different games within it!
</p>

<ul>
  <% @genre.games.each do |game| %>
    <li>
      <%= link_to game.game_name, game %> with a price of <%= game.price %>$
    </li>
  <% end %>
</ul>

app/views/publisher/index.html.erb
<h2 class = "title is-2">Publisher#index</h2>
<table class = "table">
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
  <% @publishers.each do |publisher| %>
    <tr>
      <td><%= link_to publisher.publisher_name, publisher %></td>
    </tr>
  <% end %>
  </tbody>
</table>
  <%= paginate @publishers %>

app/views/publisher/show.html.erb
<h1>Publishers#show</h1>
<h2 class="title is-2"><%= @publisher.publisher_name %></h2>

<p>
  <%= @publisher.publisher_name %> has created <%= @publisher.games.count %> different Games!
</p>

<ul>
  <% @publisher.games.each do |game| %>
    <li>
      <%= link_to game.game_name, game %> with a price of <%= game.price %>$
    </li>
  <% end %>
</ul>