config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :game, only: %i[index show] do
    collection do
      get "search"
    end
  end
  resources :cart, only: %i[create destroy]
  resources :publisher, only: %i[index show]
  resources :platform, only: %i[index show]
  resources :genre, only: %i[index show]
  get "welcome/index"
  root "welcome#index"
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  scope "/checkout" do
    post "create", to: "checkout#create", as: "checkout_create"
    get "success", to: "checkout#success", as: "checkout_success"
    get "cancel", to: "checkout#cancel", as: "checkout_cancel"
    get "view", to: "checkout#view", as: "checkout_view"
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :genre
  belongs_to :platform
  belongs_to :publisher

  validates :game_name, :price, :release_year, presence: true
  validates :game_name, uniqueness: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games, dependent: :destory

  validates :genre_name, presence: true
  validates :genre_name, uniqueness: true
end

app/models/platform.rb
class Platform < ApplicationRecord
  has_many :games, dependent: :destory

  validates :platform_name, presence: true
  validates :platform_name, uniqueness: true
end

app/models/province.rb
class Province < ApplicationRecord
  has_many :users, dependent: :destory
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :games, dependent: :destory

  validates :publisher_name, presence: true
  validates :publisher_name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :province
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :address, :city, presence: true
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  # POST /cart
  # data is sent as form data (params)
  def create
    id = params[:id].to_i
    return if session[:shopping_cart].include?(id)

    session[:shopping_cart] << id # push id onto the end of the cart array
    game = Game.find(id)
    flash[:notice] = "➕ #{game.game_name} added to cart!"
  end
end

# DELETE /cart/:id
def destroy
  id = params[:id].to_i
  session[:shopping_cart].delete(id)
  game = Game.find(id)
  flash[:notice] = "➖ #{game.game_name} removed from cart!"
end

app/controllers/game_controller.rb
class GameController < ApplicationController
  def index
    @games = Game.includes(:genre).page params[:page]
  end

  def show
    @game = Game.find(params[:id])
  end

  def search
    wildcard_search = "%#{params[:keywords]}%"
    @games_search = Game.where("game_name LIKE ?", wildcard_search)
  end
end

app/controllers/genre_controller.rb
class GenreController < ApplicationController
  def index
    @genres = Genre.page params[:page]
  end

  def show
    @genre = Genre.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @games = Game.all.limit(6)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/platform_helper.rb
module PlatformHelper
end

app/helpers/publisher_helper.rb
module PublisherHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "Video Game Store!", welcome_index_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", welcome_index_path, class: "nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to "Games", game_index_path, class: "nav-link" %>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            More Stuff!
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Publishers!", publisher_index_path, class: "dropdown-item" %></li>
            <li><%= link_to "Platforms!", platform_index_path, class: "dropdown-item" %></li>
            <li><%= link_to "Genre!", genre_index_path, class: "dropdown-item" %></li>
          </ul>
        </li>

      <% if user_signed_in? %>

        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link"%>
        </li>

        <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>

      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Cart!", checkout_view_path, class: "nav-link" %>
        </li>

      <% end %>

      </ul>
        <div class="d-flex">
          <%= form_with(url: search_game_index_path, method: :get, local: true) do |form| %>
          <%= form.label :keywords, "Search for: " %>
          <%= form.text_field :keywords %>
          <% end %>
          <%= submit_tag("Search", class: "button is-primary") %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoGameStore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://js.stripe.com/v3"></script>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar"%>
      <% if flash[:notice] %>
        <p class = "notice"><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:alert] %>
        <p class = "alert"><%= flash[:alert] %></p>
      <% end %>

    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>